# PostgreSQL. Versions 9.1 and up are supported.
#
# Configure Using Gemfile
# gem 'pg'
default: &default
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host: localhost
  port: 5432
  username: bitz
  password: bitz_gfhjkm
  database: bitz
  schema_search_path: public
  encoding: utf8
  template: template1
  reconnect: true


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
